### ISSUE TITLE
Don't ignore JSON decoding errors

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/py-algorand-sdk#193]
## Summary
Currently if a JSON algod request cannot parse the response, it just returns `None`: https://github.com/algorand/py-algorand-sdk/blob/6b304e4b080d95286f836d8cd6d8cc3aeeefdfd5/algosdk/v2client/algod.py#L81-L84

## Scope
We should really return an error message in this case instead.

## Urgency
It's important to display the proper error if decoding is unsuccessful.

**Comment by jkschin** [comment]
Hey @jasonpaulos, are you taking PRs for this? I've got two ideas:

1. Instead of returning `None`, we `raise json.JSONDecodeError`.
2. Inside `error.py`, create a class named `AlgodJSONDecodeError` and customize the messages.

Is there a place I should be writing a test for this as well? I can't find it. Happy to contribute a short PR and get familiar with Algorand.

**Comment by jasonpaulos** [comment]
@jkschin we would definitely appreciate a PR for this! Currently there is no easy way to automate a test for this (unless we can mock algod 🤔), so in this case I'd be inclined to accept a PR without a test.
