### ISSUE TITLE
Move/rename "tests" module

### ISSUE THREAD

**Issue by MaxKh** [algorand/py-algorand-sdk#374]
## Problem

The py-algorand-sdk's "tests" module may conflict with a local one. I believe that "tests" is a quite popular name for a projects' UTs.

## Solution

Please rename "tests", move into "algosdk" or ship "tests" as "extras" which allows to exclude this module from installation.

**Comment by winder** [comment]
@tzaffi are you familiar with this issue?

**Comment by tzaffi** [comment]
I was involved in reviewing #351 which renamed the `test` directory to `tests`. As a starting point to help investigate a solution, @MaxKh - could you provide a reproducible method to observe the conflict? For example, a github repo with instructions for building but which gets stuck because of this naming issue.

**Comment by tzaffi** [comment]
Also, @jasonpaulos might have some more familiarity with the history of why we chose `test` for the SDK's testing directory starting out.

**Comment by jasonpaulos** [comment]
`test`/`tests` is a pretty common convention for testing directories, and I think it's in our best interests to keep the directory structure like this. If implemented properly, our choice of internal directory names should not cause any problems for consumers of this library.

Perhaps the issue is that our `tests` folder is unintentionally being picked by `setuptools` as a package we wish to export? We do ask `setuptools` to automatically find all packages: https://github.com/algorand/py-algorand-sdk/blob/e39f97ce6c302448814480b16d528cbdcabbbd93/setup.py#L24

If this is the case, there are [alternatives](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html) we could consider, but we first need a reproducible example to be sure.

**Comment by algochoi** [comment]
We no longer ship `tests` as a part of the `py-algorand-sdk` installation, as of #428 . Let us know if this resolves the issue!
